### ISSUE TITLE
Add mention to commonly used commands

### ISSUE THREAD

**Issue by pajlada** [pajlada/plugdj-pajbot#15]
For .tp or .newfag

.tp:
https://fungustime.pw/tastyplug/

.tp PAJLADA
@PAJLADA https://fungustime.pw/tastyplug/
.tp @PAJLADA
@PAJLADA https://fungustime.pw/tastyplug/
.tp @NONEXISTANTUSER
https://fungustime.pw/tastyplug/

**Comment by Leti460** [comment]
New assist function added to context.js in https://github.com/pajlada/pajbot/commit/23eb257b58ba79c0649d52cbd0cf3eec83888549
Usable for all similar commands.
