### ISSUE TITLE
!swapreq

### ISSUE THREAD

**Issue by pajlada** [pajlada/plugdj-pajbot#2]
Halokitty and MRCRYSIS want to swap places in the queue.
Halokitty is at position 7 and MRCRYSIS is at position 33.

Halokitty initiates the swap request by typing:
!swapreq @MRCRYSIS
Bot replies:
/me @MRCRYSIS You have been requested to swap places with @Halokitty. Type !swapreq @Halokitty to accept.

MRCRYSIS accepts the request by typing:
!swapreq @Halokitty
The bot then proceeds to swap Halokitty and MRCRYSIS.

**Comment by Leti460** [comment]
Added in https://github.com/pajlada/pajbot/commit/7f759d70e8a2f24a28c3e0e82b6a08a33c3ece60
(Possibly) finalized in https://github.com/pajlada/pajbot/commit/b4e57f164e460496996ada5727100df22efdffdb
