### ISSUE TITLE
brawl

### ISSUE THREAD

**Issue by ghost** [pajlada/plugdj-pajbot#30]
fuck you pajlada
fuck you pajlada

**Comment by ghost** [comment]
.brawl

**Comment by ghost** [comment]
60 sec time evryone in waitlist can join
when atleast 5 guys join the brawl starts after 60 sec if not return "not enough brawlers" or whatever
if brawl starts pick a winner winner gets moved to postion 1 rest of the brawlers get removed from waitlist

**Comment by pajlada** [comment]
We have enough fighting commands.
